name: flutter_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.8.1 <4.0.0"   # Dart SDK
  flutter: ">=3.29.0"     # Alineado con el lock; podemos subir luego si ya estás en 3.35.x

dependencies:
  flutter:
    sdk: flutter

  # Core
  http: ^1.5.0
  provider: ^6.1.5
  intl: ^0.19.0

  # Storage local
  drift: ^2.29.0
  sqlite3_flutter_libs: ^0.5.40
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  path_provider: ^2.1.5
  path: ^1.9.1

  # Red / utilidades
  dio: ^5.9.0
  connectivity_plus: ^6.1.5
  url_launcher: ^6.3.2

  # UI / Media
  cached_network_image: ^3.4.1
  image_picker: ^1.2.0
  google_maps_flutter: ^2.13.1
  google_fonts: ^6.3.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Drift codegen
  drift_dev: ^2.29.0
  build_runner: ^2.10.1

  # Lints
  flutter_lints: ^5.0.0
  fl_chart: ^1.1.0


flutter:
  uses-material-design: true
  # assets:
  #   - assets/images/
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700
